### ISSUE TITLE
No odbcinst and can not load driver

### ISSUE THREAD

**Issue by aimengda** [cloudfoundry/cflinuxfs4#10]
Hi,

I found there are no below items in cflinuxfs4 but they do exist in cflinuxfs3, so any idea on how to load SQL SERVER ODBC driver on cflinuxfs4?

odbcinst                           2.3.4-1.1ubuntu3                    amd64        Helper program for accessing odbc ini files
odbcinst1debian2:amd64             2.3.4-1.1ubuntu3                    amd64        Support library for accessing odbc ini files

**Comment by aimengda** [comment]
Yes i'm having issue loading the MS SQL ODBC driver, the error is that no odbcinst installed when I call the odbcinst command

**Comment by aimengda** [comment]
Adding error msg for reference?

**Comment by robdimsdale** [comment]
I can easily reproduce this:

### cflinuxfs3

```
→ docker run --rm -it cloudfoundry/cflinuxfs3 odbcinst

**********************************************
* unixODBC - odbcinst                        *
**********************************************
<...>
```

### cflinuxfs4

```
 → docker run --rm -it cloudfoundry/cflinuxfs4 odbcinst
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "odbcinst": executable file not found in $PATH: unknown.
```

I can easily `apt update && apt install odbcinst` and get this executable on `cflinuxfs4`. I think we should explicitly add it to the package list.

**Comment by sophiewigmore** [comment]
Hmm, I see. It does seem problematic that the packages to use the ODBC driver are no longer pulled in, although it seems like the `odbcinst` package was removed for a reason. We should probably just pull it in for completeness

**Comment by aimengda** [comment]
I'm using the buildpack on-prem on VMware Tanzu, so unable to use the apt update & apt install, so really need to waiting for the official fix.

**Comment by sophiewigmore** [comment]
@aimengda cflinuxfs4 stack v1.26.0 (https://github.com/cloudfoundry/cflinuxfs4/releases/tag/1.26.0) and above have the packages you asked about included in them. Are you not able to use that stack?

**Comment by aimengda** [comment]
Seems not, I'm using Python buildpack so I need to wait for the new version of Python buildpack which based on the new cfslinuxfs4

**Comment by sophiewigmore** [comment]
The python buildpack and the cflinuxfs4 are separate, and the python buildpack has cflinuxfs4 support, so you'd just need to upgrade to the newer version. This is an open-source cloudfoundry issue, so I'd recommend going through official channels for your Tanzu concerns if you have questions about how to upgrade. 
In terms of resolving the core of this issue, I believe we resolved it with the changes we released in v1.26.0 so I'm closing this out. If you try out the stack and you still have an issue, please reopen this!

**Comment by aimengda** [comment]
Get it, let me reach my IT for support.

**Comment by aimengda** [comment]
@sophiewigmore Does VmWare have plan to update the cflinuxfs4 to v1.26.0 and above on next release(4.0.6)?
