### ISSUE TITLE
Add snap to installed packages

### ISSUE THREAD

**Issue by mohadipe** [cloudfoundry/cflinuxfs4#18]
I am interested in including snap in cflinuxfs4 because I want to install the chromium-browser package in my app.
With cflinuxfs3 I currently do this with the apt_buildpack.
But for Ubuntu 22 there is no PPA that I can use.
If I use the apt_buildpack as before the chromium-browser is not installed correctly.
If I want to run it I get an error message that snap is required.

Is there anything against including snap as a package?

**Comment by sophiewigmore** [comment]
What's the error message you encounter when you try to use the apt buildpack?

**Comment by mohadipe** [comment]
Hi,

at the time of installation we do not receive an error message.
When we want to start the application we get the following message.

> ./chromium-browser
> Command './chromium-browser' requires the chromium snap to be installed.
> Please install it with:
> snap install chromium

**Comment by sophiewigmore** [comment]
Ah I see. In this case I don't think it makes sense to install snap onto the stack because even if it's installed, you'll still need a way to run `snap install chromium` which doesn't exist as far as I know. In general I think I'm against adding it to the stack because it leads to a confusing use case for users who then don't have a clear way to leverage snap

**Comment by sophiewigmore** [comment]
You could maybe consider making a [custom stack](https://docs.cloudfoundry.org/running/custom-stack.html) - or looking at a different PPA (https://launchpad.net/~phd/+archive/ubuntu/chromium-browser mentions https://freeshell.de/phd/chromium).

**Comment by mohadipe** [comment]
Thanks for your tip and your answer.

I think the ticket can be closed.

Merry Christmas :christmas_tree:

**Comment by sophiewigmore** [comment]
You too! ⭐
