### ISSUE TITLE
ping: socket: Address family not supported by protocol

### ISSUE THREAD

**Issue by sunny-repo88** [cloudfoundry/cflinuxfs4#6]
After migrate from cflinuxfs3 to cflinuxfs4, we are facing this error

```
ping google.com
ping: socket: Address family not supported by protocol
```

**Comment by sophiewigmore** [comment]
Hey @sunny-repo88, can you provide a bit more information about your app? Which buildpacks are you using?

**Comment by arjun024** [comment]
See https://github.com/cloudfoundry/cflinuxfs4-release/pull/5. The fix will be available in the next release
